R_ANKLE = 0
R_KNEE = 1
R_HIP = 2
L_HIP = 3
L_KNEE = 4
L_ANKLE = 5
PELVIS = 6
SPINE = 7
NECK = 8
HEAD_TOP = 9
R_WRIST = 10
R_ELBOW = 11
R_SHOULDER = 12
L_SHOULDER = 13
L_ELBOW = 14
L_WRIST = 15

MPII_BONES = [
    [R_KNEE, R_ANKLE],
    [R_HIP, R_KNEE],
    [R_HIP, PELVIS],
    [L_HIP, PELVIS],
    [L_HIP, L_KNEE],
    [L_KNEE, L_ANKLE],
    [PELVIS, SPINE],
    [SPINE, NECK],
    [NECK, HEAD_TOP],
    [R_WRIST, R_ELBOW],
    [R_ELBOW, R_SHOULDER],
    [NECK, R_SHOULDER],
    [NECK, L_SHOULDER],
    [L_SHOULDER, L_ELBOW],
    [L_ELBOW, L_WRIST]
]

MPII_BONES_NAMES = [
    "RIGHT_LOWER_LEG",
    "RIGHT_UPPER_LEG",
    "RIGHT_LEG_JOINT",
    "LEFT_LEG_JOINT",
    "LEFT_UPPER_LEG",
    "LEFT_LOWER_LEG",
    "LOWER_SPINE",
    "UPPER_SPINE",
    "HEAD_TO_NECK",
    "RIGHT_LOWER_ARM",
    "RIGHT_UPPER_ARM",
    "RIGHT_SHOULDER_JOINT",
    "LEFT_SHOULDER_JOINT",
    "LEFT_UPPER_ARM",
    "LEFT_LOWER_ARM"
]

RIGHT_LOWER_LEG = 0
RIGHT_UPPER_LEG = 1
RIGHT_LEG_JOINT = 2
LEFT_LEG_JOINT = 3
LEFT_UPPER_LEG = 4
LEFT_LOWER_LEG = 5
LOWER_SPINE = 6
UPPER_SPINE = 7
HEAD_TO_NECK = 8
RIGHT_LOWER_ARM = 9
RIGHT_UPPER_ARM = 10
RIGHT_SHOULDER_JOINT = 11
LEFT_SHOULDER_JOINT = 12
LEFT_UPPER_ARM = 13
LEFT_LOWER_ARM = 14

MPII_ANGLES = [
    [RIGHT_LOWER_LEG, RIGHT_UPPER_LEG],
    [LEFT_LOWER_LEG, LEFT_UPPER_LEG],
    [LEFT_LEG_JOINT, LEFT_UPPER_LEG], # less important
    [RIGHT_LEG_JOINT, RIGHT_UPPER_LEG], # less important
    [UPPER_SPINE, HEAD_TO_NECK], # possibly take out later
    [UPPER_SPINE, LOWER_SPINE],
    [RIGHT_LOWER_ARM, RIGHT_UPPER_ARM],
    [RIGHT_SHOULDER_JOINT, RIGHT_UPPER_ARM],
    [RIGHT_SHOULDER_JOINT, HEAD_TO_NECK], # less important
    [LEFT_LOWER_ARM, LEFT_UPPER_ARM],
    [LEFT_SHOULDER_JOINT, LEFT_UPPER_ARM],
    [LEFT_SHOULDER_JOINT, HEAD_TO_NECK] # less important
]

MPII_ANGLES_NAMES = [
    "[RIGHT_LOWER_LEG, RIGHT_UPPER_LEG]",
    "[LEFT_LOWER_LEG, LEFT_UPPER_LEG]",
    "[LEFT_LEG_JOINT, LEFT_UPPER_LEG]", # less important
    "[RIGHT_LEG_JOINT, RIGHT_UPPER_LEG]", # less important
    "[UPPER_SPINE, HEAD_TO_NECK]", # possibly take out later
    "[UPPER_SPINE, LOWER_SPINE]",
    "[RIGHT_LOWER_ARM, RIGHT_UPPER_ARM]",
    "[RIGHT_SHOULDER_JOINT, RIGHT_UPPER_ARM]",
    "[RIGHT_SHOULDER_JOINT, HEAD_TO_NECK]", # less important
    "[LEFT_LOWER_ARM, LEFT_UPPER_ARM]",
    "[LEFT_SHOULDER_JOINT, LEFT_UPPER_ARM]",
    "[LEFT_SHOULDER_JOINT, HEAD_TO_NECK]" # less important
]


MPII_ANGLE_ROMS = [
    150, # [RIGHT_LOWER_LEG, RIGHT_UPPER_LEG],
    150, # [LEFT_LOWER_LEG, LEFT_UPPER_LEG],
    100, # [LEFT_LEG_JOINT, LEFT_UPPER_LEG],
    100, # [RIGHT_LEG_JOINT, RIGHT_UPPER_LEG], 
    60, # [UPPER_SPINE, HEAD_TO_NECK], 
    90, # [UPPER_SPINE, LOWER_SPINE],
    170, # [RIGHT_LOWER_ARM, RIGHT_UPPER_ARM],
    170, # [RIGHT_SHOULDER_JOINT, RIGHT_UPPER_ARM],
    50, # [RIGHT_SHOULDER_JOINT, HEAD_TO_NECK], 
    170, # [LEFT_LOWER_ARM, LEFT_UPPER_ARM],
    170, # [LEFT_SHOULDER_JOINT, LEFT_UPPER_ARM],
    50, # [LEFT_SHOULDER_JOINT, HEAD_TO_NECK] 
]
